// Email formatting and sending using Resend
import { Resend } from "resend";
import { Lead } from "./types.js";

/**
 * Format leads into a nice HTML email
 */
export function formatLeadsEmail(
  leads: Lead[],
  searchDate: Date
): { subject: string; html: string } {
  const hotLeads = leads.filter((l) => l.leadScore >= 60);
  const warmLeads = leads.filter((l) => l.leadScore >= 30 && l.leadScore < 60);
  const coldLeads = leads.filter((l) => l.leadScore < 30);

  const dateStr = searchDate.toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const subject = `🎯 ${leads.length} Website Leads for ${dateStr}`;

  const html = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }
    h1 { color: #2563eb; border-bottom: 2px solid #2563eb; padding-bottom: 10px; }
    h2 { color: #374151; margin-top: 30px; }
    .lead-card { background: #f9fafb; border-radius: 8px; padding: 16px; margin: 12px 0; border-left: 4px solid #e5e7eb; }
    .lead-card.hot { border-left-color: #ef4444; background: #fef2f2; }
    .lead-card.warm { border-left-color: #f59e0b; background: #fffbeb; }
    .lead-card.cold { border-left-color: #6b7280; }
    .business-name { font-size: 18px; font-weight: 600; color: #111827; margin: 0 0 8px 0; }
    .score { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 12px; font-weight: 600; }
    .score.hot { background: #fee2e2; color: #991b1b; }
    .score.warm { background: #fef3c7; color: #92400e; }
    .score.cold { background: #e5e7eb; color: #374151; }
    .details { font-size: 14px; color: #6b7280; margin: 4px 0; }
    .reason { font-size: 14px; color: #059669; font-weight: 500; margin-top: 8px; }
    .issues { font-size: 13px; color: #dc2626; margin-top: 4px; }
    .contact { margin-top: 8px; }
    .contact a { color: #2563eb; text-decoration: none; }
    .contact a:hover { text-decoration: underline; }
    .summary { background: #eff6ff; border-radius: 8px; padding: 16px; margin: 20px 0; }
    .summary-stat { display: inline-block; margin-right: 24px; }
    .summary-stat .number { font-size: 24px; font-weight: 700; color: #2563eb; }
    .summary-stat .label { font-size: 12px; color: #6b7280; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #9ca3af; }
  </style>
</head>
<body>
  <h1>🎯 Weekly Website Leads</h1>
  <p>Here are your leads for <strong>${dateStr}</strong> - businesses in Hartford County, CT that need a website.</p>

  <div class="summary">
    <div class="summary-stat">
      <div class="number">${leads.length}</div>
      <div class="label">Total Leads</div>
    </div>
    <div class="summary-stat">
      <div class="number">${hotLeads.length}</div>
      <div class="label">🔥 Hot Leads</div>
    </div>
    <div class="summary-stat">
      <div class="number">${warmLeads.length}</div>
      <div class="label">⚡ Warm Leads</div>
    </div>
  </div>

  ${
    hotLeads.length > 0
      ? `
  <h2>🔥 Hot Leads (Score 60+)</h2>
  <p>These businesses urgently need a website - prioritize these!</p>
  ${hotLeads.map((lead) => formatLeadCard(lead, "hot")).join("")}
  `
      : ""
  }

  ${
    warmLeads.length > 0
      ? `
  <h2>⚡ Warm Leads (Score 30-59)</h2>
  <p>These businesses could use a website upgrade.</p>
  ${warmLeads.map((lead) => formatLeadCard(lead, "warm")).join("")}
  `
      : ""
  }

  ${
    coldLeads.length > 0
      ? `
  <h2>❄️ Other Leads (Score <30)</h2>
  <p>Lower priority but still potential opportunities.</p>
  ${coldLeads.map((lead) => formatLeadCard(lead, "cold")).join("")}
  `
      : ""
  }

  <div class="footer">
    <p>Generated by your Lead Finder automation on Trigger.dev</p>
    <p>Search area: 20 miles from Bloomfield, CT (06002)</p>
  </div>
</body>
</html>
  `.trim();

  return { subject, html };
}

function formatLeadCard(
  lead: Lead,
  priority: "hot" | "warm" | "cold"
): string {
  const b = lead.business;
  const w = lead.websiteAnalysis;

  const websiteStatus = !b.website
    ? "❌ No website"
    : !w?.exists
      ? "⚠️ Website broken"
      : `🔗 ${b.website}`;

  const issues = w?.issues?.length
    ? `<div class="issues">Issues: ${w.issues.join(", ")}</div>`
    : "";

  return `
    <div class="lead-card ${priority}">
      <div style="display: flex; justify-content: space-between; align-items: start;">
        <h3 class="business-name">${escapeHtml(b.name)}</h3>
        <span class="score ${priority}">Score: ${lead.leadScore}</span>
      </div>
      <div class="details">📍 ${escapeHtml(b.address)}</div>
      <div class="details">📂 ${escapeHtml(b.category)}</div>
      <div class="details">${websiteStatus}</div>
      ${b.rating ? `<div class="details">⭐ ${b.rating} (${b.reviewCount || 0} reviews)</div>` : ""}
      <div class="reason">💡 ${escapeHtml(lead.reason)}</div>
      ${issues}
      <div class="contact">
        ${b.phone ? `<a href="tel:${b.phone}">📞 ${b.phone}</a>` : ""}
        ${b.website ? ` • <a href="${b.website}" target="_blank">🌐 View Site</a>` : ""}
      </div>
    </div>
  `;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

/**
 * Send the leads email using Resend
 */
export async function sendLeadsEmail(
  to: string,
  leads: Lead[]
): Promise<{ success: boolean; messageId?: string; error?: string }> {
  const apiKey = process.env.RESEND_API_KEY;
  if (!apiKey) {
    throw new Error("RESEND_API_KEY is not set");
  }

  const resend = new Resend(apiKey);
  const { subject, html } = formatLeadsEmail(leads, new Date());

  console.log(`Sending ${leads.length} leads to ${to}`);

  try {
    const { data, error } = await resend.emails.send({
      from: "Lead Finder <onboarding@resend.dev>", // Use your verified domain in production
      to: [to],
      subject,
      html,
    });

    if (error) {
      console.error("Resend error:", error);
      return { success: false, error: error.message };
    }

    console.log("Email sent successfully:", data?.id);
    return { success: true, messageId: data?.id };
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    console.error("Failed to send email:", message);
    return { success: false, error: message };
  }
}
